### ISSUE TITLE
Feature Request: Wordpress Import

### ISSUE THREAD

**Issue by jcrawford** [ludovicchabant/PieCrust#107]
When PieCrust is importing the posts/pages it should also pull down any images which are used in posts.  While it has pulled down all of my posts and pages, I now have to go through and pull down my images and edit all of the files so that it can find the images.

**Comment by ludovicchabant** [comment]
Nobody implemented it for PieCrust 1.x, but I did it for [PieCrust 2.x](http://bolt80.com/piecrust/en/latest/docs/importing/wordpress/).
