### ISSUE TITLE
Recipes for site setups needed

### ISSUE THREAD

**Issue by snassar** [ludovicchabant/PieCrust#137]
PieCrust could use a bunch of recipes for building sites. A lot of the documentation is written "from within" and not for people coming to the project from the outside.

I am happy to contribute the writing if I had a partner who can help me with answers, pointers and steps.

**Comment by snassar** [comment]
Here are the questions I would want the documentation to help me with in the first 5-15 minutes:

## First Five Minutes
- [x] Clear installation steps
- [x] Configuration steps
  - [x] Can I find all the config options for a site easily in a reference page?
- [x] Give an overview about the interplay of the different pieces: Twig, PieCrust, etc.
- [x] How do I create pages?
  - [x] Why would I use 'chef prepare page' vs. creating a text file from scratch?
  - [x] Can I find all the config options for a page easily in a reference page?
- [x] How do I create a blog?
  - [x] Why would I use 'chef prepare page' vs. creating a text file from scratch?
  - [x] Give more detail about the blog-specific options
- [ ] Explain how one can start themeing their site

## First Thirty Minutes
- [ ] Reference examples of templating
- [ ] Reference example of themeing

## Reference
- [x] Available function list with explanation and examples.
- [ ] A reference theme people can use that exposes the most functionality. (I am working on a Bootstrap 3 + Fontawesome 4 theme)
- [x] A few reference templates with documentation

**Comment by ludovicchabant** [comment]
I came back to this list a few times while writing the [new documentation](http://bolt80.com/piecrust). It's missing documentation on themes and plugins but the rest is good I think. Thanks!
