### ISSUE TITLE
Baking from _index.md not working

### ISSUE THREAD

**Issue by gerundt** [ludovicchabant/PieCrust#141]
I try to bake a simple website, but it seems that PieCrust ignore/overwrite my "_index.md" file:

	[_content]
	  [pages]
		_index.md
		test.md
	  [templates]
		default.html
	  config.yml

If I rename the file to "_index.html" everything is OK, but with "_index.md" he create only a "Quick Start" page. Other *.md file works like expected.

The output from chef looks like, as overwrite he my index file, since he output **[main page]** twice:

	chef.cmd bake
	[    77.0 ms] cleaned cache (reason: not valid anymore)
	[   133.7 ms] [main page]
	[    15.3 ms] test
	[     1.7 ms] [main page]
	-------------------------
	[   261.3 ms] done baking

Greetings,
Tim

**Comment by ludovicchabant** [comment]
Fixing this in the 1.x codebase was difficult. It's working fine in 2.0 though so I'll close this.
