### ISSUE TITLE
Breadcrumbs recipe?

### ISSUE THREAD

**Issue by mithat** [ludovicchabant/PieCrust#154]
Here is what I'm currently using to implement breadcrumbs (against Bootstrap's CSS, but should work more generally):

`_content/pages/brooklynbridge.md`:
~~~
---
title: Brooklyn Bridge
layout: item
date: 2014-08-02 20:07
parents: [ ['Home', '/'],  ['Products', 'product'] ]
---

Awesome bridge with only slight wear. Clean title. Ready for immediate occupancy.
~~~~

`_content/templates/item.html`:
~~~
...

    <ul class="breadcrumb">
    {% for pr in page.parents %}
        <li><a href="{{ pcurl(pr[1]) }}">{{ pr[0] }}</a></li>
    {%endfor%}
        <li class="active">{{ page.title }}</li>
    </ul>

...
~~~

Is there a less bad way to do it?

**Comment by ludovicchabant** [comment]
Fixed in PieCrust 2 (see [this change](https://github.com/ludovicchabant/PieCrust2/commit/2ec46b0397d071b8bb7a0190b72fe5872ff30796)). You can go `{% for p in family.ancestors %}` and get all the parents all the way to the root.
